name: ALL/PM - Issue ìë™ ê´€ë¦¬

on:
  issues:
    types: [assigned, closed]

env:
  # GitHub ì‚¬ìš©ì ì´ë¦„ â†’ Slack ID ë§¤í•‘
  ASSIGNEE_SLACK_ID: ${{ secrets.ASSIGNEE_SLACK_ID }}
  dydals3440: ${{ secrets.ASSIGNEE_SLACK_ID }}


jobs:
  create-issue-branch:
    name: "feature ì´ìŠˆ í• ë‹¹ -> ë¸Œëœì¹˜-PR ìë™ ìƒì„±"
    runs-on: ubuntu-latest
    if: github.event.action == 'assigned'
    steps:
      - name: create the issue branch
        uses: robvanderleek/create-issue-branch@1.7.0
        id: create-issue-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-open-issue:
    name: "ì´ìŠˆ ì‘ì—… ì‹œì‘ -> Slack ì±„ë„ ì•Œë¦¼"
    runs-on: ubuntu-latest
    if: github.event.action == 'assigned'
    steps:
      - name: Set assignee Slack ID from GitHub assignee
        id: set-vars
        run: |
          ASSIGNEE_LOGIN="${{ github.event.issue.assignee.login }}"
          echo "GitHub assignee: $ASSIGNEE_LOGIN"
          ASSIGNEE_SLACK_ID=$(printenv "$ASSIGNEE_LOGIN")
          echo "ASSIGNEE_SLACK_ID: $ASSIGNEE_SLACK_ID"
          echo "ASSIGNEE_SLACK_ID=$ASSIGNEE_SLACK_ID" >> ${GITHUB_ENV}

      - name: ì‘ì—… ì‹œì‘ -> Slack ì±„ë„ ì•Œë¦¼
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.IN_PROGRESS_SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "ğŸ”” ì‘ì—… ì‹œì‘ ì•Œë¦¼ ğŸ””",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "ã€°ï¸ã€°ã€°ï¸ã€° \nğŸš€ ì‘ì—… ì‹œì‘ \n <@${{ env.ASSIGNEE_SLACK_ID }}> ë‹˜ì´ \n <${{ github.event.issue.html_url }}|${{ github.event.issue.title }}> ì‘ì—…ì„ ì‹œì‘í–ˆìŠµë‹ˆë‹¤!:muscle:"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  notify-close-issue:
    name: "ì´ìŠˆ ì‘ì—… ì¢…ë£Œ -> Slack ì±„ë„ ì•Œë¦¼"
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Set assignee Slack ID from GitHub assignee
        id: set-vars
        run: |
          ASSIGNEE_LOGIN="${{ github.event.issue.assignee.login }}"
          echo "GitHub assignee: $ASSIGNEE_LOGIN"
          ASSIGNEE_SLACK_ID=$(printenv "$ASSIGNEE_LOGIN")
          echo "ASSIGNEE_SLACK_ID: $ASSIGNEE_SLACK_ID"
          echo "ASSIGNEE_SLACK_ID=$ASSIGNEE_SLACK_ID" >> ${GITHUB_ENV}
          
      - name: ì‘ì—… ì¢…ë£Œ -> Slack ì±„ë„ ì•Œë¦¼
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.TASK_COMPLETE_SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "ğŸ‰ ì‘ì—… ì™„ë£Œ ì•Œë¦¼ ğŸ‰",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "ã€°ï¸ã€°ã€°ï¸ã€° \n:pushpin:ì‘ì—… ì™„ë£Œ\n <@${{ env.ASSIGNEE_SLACK_ID }}> ë‹˜ì˜ í• ë‹¹ ì´ìŠˆì¸ \n\n:confetti_ball: <${{ github.event.issue.html_url }}|${{ github.event.issue.title }}> ì‘ì—…ì´ ì™„ë£Œ(ì¢…ë£Œ)ëìŠµë‹ˆë‹¤! :confetti_ball:"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
